package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 16 13:45:27 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailExternalReferenceImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DetailExternalReferenceImpl() {
    }

    /**
     * Returns the bind variable value for transmittalID.
     * @return bind variable value for transmittalID
     */
    public String gettransmittalID() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
    }

    /**
     * Sets <code>value</code> for bind variable transmittalID.
     * @param value value to bind as transmittalID
     */
    public void settransmittalID(String value) {
        setNamedWhereClauseParam("transmittalID", value);
    }
}
