package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 16 13:06:32 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailInternalSupportingDocForDelegateImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DetailInternalSupportingDocForDelegateImpl() {
    }

    /**
     * Returns the bind variable value for transmittal_id.
     * @return bind variable value for transmittal_id
     */
    public String gettransmittal_id() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
    }

    /**
     * Sets <code>value</code> for bind variable transmittal_id.
     * @param value value to bind as transmittal_id
     */
    public void settransmittal_id(String value) {
        setNamedWhereClauseParam("transmittal_id", value);
    }

    /**
     * Returns the bind variable value for username.
     * @return bind variable value for username
     */
    public String getusername() {
        return (String)getNamedWhereClauseParam("username");
    }

    /**
     * Sets <code>value</code> for bind variable username.
     * @param value value to bind as username
     */
    public void setusername(String value) {
        setNamedWhereClauseParam("username", value);
    }
}
