package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 20 12:29:37 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IsUserFinishedImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IsUserFinishedImpl() {
    }

    /**
     * Returns the bind variable value for transmittalId.
     * @return bind variable value for transmittalId
     */
    public String gettransmittalId() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
    }

    /**
     * Sets <code>value</code> for bind variable transmittalId.
     * @param value value to bind as transmittalId
     */
    public void settransmittalId(String value) {
        setNamedWhereClauseParam("transmittalId", value);
    }

    /**
     * Returns the bind variable value for dUser.
     * @return bind variable value for dUser
     */
    public String getdUser() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("dUser").toString();
    }

    /**
     * Sets <code>value</code> for bind variable dUser.
     * @param value value to bind as dUser
     */
    public void setdUser(String value) {
        setNamedWhereClauseParam("dUser", value);
    }
}
