package transmittalExternal.vo;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 20 16:35:29 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PheDswfDocSubmittalVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PheDswfDocSubmittalVOImpl() {
    }

    /**
     * Returns the bind variable value for transmittal_id.
     * @return bind variable value for transmittal_id
     */
    public String gettransmittal_id() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString().trim();
    }

    /**
     * Sets <code>value</code> for bind variable transmittal_id.
     * @param value value to bind as transmittal_id
     */
    public void settransmittal_id(String value) {
        setNamedWhereClauseParam("transmittal_id", value);
    }

    /**
     * Returns the bind variable value for uploader.
     * @return bind variable value for uploader
     */
    public String getuploader() {
        if(AdfFacesContext.getCurrentInstance().getPageFlowScope().get("isTdc") != null){ 
            if(AdfFacesContext.getCurrentInstance().getPageFlowScope().get("isTdc").toString().equalsIgnoreCase("true")){
                return "%";
            }else{
                FacesContext ctx = FacesContext.getCurrentInstance();
                HttpServletRequest requestSession = (HttpServletRequest)ctx.getExternalContext().getRequest();
                HttpSession session =  requestSession.getSession(true);
//                return session.getAttribute("username").toString();
                return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("dUser").toString();
            }
        }else{
            FacesContext ctx = FacesContext.getCurrentInstance();
            HttpServletRequest requestSession = (HttpServletRequest)ctx.getExternalContext().getRequest();
            HttpSession session =  requestSession.getSession(true);
//            return session.getAttribute("username").toString();
            return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("dUser").toString();
        }
    }

    /**
     * Sets <code>value</code> for bind variable uploader.
     * @param value value to bind as uploader
     */
    public void setuploader(String value) {
        setNamedWhereClauseParam("uploader", value);
    }
}
