package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 13 02:18:20 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PheDelegateViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PheDelegateViewImpl() {
    }

    /**
     * Returns the bind variable value for transmittalID.
     * @return bind variable value for transmittalID
     */
    public String gettransmittalID() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId")==null?"":AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
    }

    /**
     * Sets <code>value</code> for bind variable transmittalID.
     * @param value value to bind as transmittalID
     */
    public void settransmittalID(String value) {
        setNamedWhereClauseParam("transmittalID", value);
    }

    /**
     * Returns the bind variable value for userLogin.
     * @return bind variable value for userLogin
     */
    public String getuserLogin() {
        return (String)getNamedWhereClauseParam("userLogin");
    }

    /**
     * Sets <code>value</code> for bind variable userLogin.
     * @param value value to bind as userLogin
     */
    public void setuserLogin(String value) {
        setNamedWhereClauseParam("userLogin", value);
    }
}
