package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 16 14:26:51 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TdcDetailExternalImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TdcDetailExternalImpl() {
    }

    /**
     * Returns the bind variable value for transmital_id.
     * @return bind variable value for transmital_id
     */
    public String gettransmital_id() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
    }

    /**
     * Sets <code>value</code> for bind variable transmital_id.
     * @param value value to bind as transmital_id
     */
    public void settransmital_id(String value) {
        setNamedWhereClauseParam("transmital_id", value);
    }
}
