package transmittalExternal.vo;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 14 13:08:29 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransmittalReceiverListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TransmittalReceiverListVOImpl() {
    }

    /**
     * Returns the bind variable value for transmittalId.
     * @return bind variable value for transmittalId
     */
    public String gettransmittalId() {
        return AdfFacesContext.getCurrentInstance().getPageFlowScope().get("transmittalId").toString();
        //        return (String)getNamedWhereClauseParam("transmittalId");
    }

    /**
     * Sets <code>value</code> for bind variable transmittalId.
     * @param value value to bind as transmittalId
     */
    public void settransmittalId(String value) {
        setNamedWhereClauseParam("transmittalId", value);
    }
}
