package transmittalExternal.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 27 13:28:53 ICT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateDetailSupportingDocVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidateDetailSupportingDocVoImpl() {
    }
}
