package transmittalExternal.model.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;

import transmittalExternal.model.common.AppModuleExternalTransmittal;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 04 09:19:53 ICT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleExternalTransmittalClient extends ApplicationModuleImpl implements AppModuleExternalTransmittal {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleExternalTransmittalClient() {
    }


    public Number getSeqValue(String sequenceName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSeqValue",new String [] {"java.lang.String"},new Object[] {sequenceName});
        return (Number)_ret;
    }

    public String getTransmittalType() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getTransmittalType",null,null);
        return (String)_ret;
    }

    public void SetLoadTransmittalId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"SetLoadTransmittalId",null,null);
        return;
    }

    public void ExecDetailSubmittalByUploader() {
        Object _ret =
            this.riInvokeExportedMethod(this,"ExecDetailSubmittalByUploader",null,null);
        return;
    }

    public void ExecDetailSupportingInternalByUploader() {
        Object _ret =
            this.riInvokeExportedMethod(this,"ExecDetailSupportingInternalByUploader",null,null);
        return;
    }
}
