package CID.VO;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 17 13:37:12 GMT+07:00 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class apListLovVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        KeyValue {
            public Object get(apListLovVORowImpl obj) {
                return obj.getKeyValue();
            }

            public void put(apListLovVORowImpl obj, Object value) {
                obj.setKeyValue((String)value);
            }
        }
        ,
        Dusername {
            public Object get(apListLovVORowImpl obj) {
                return obj.getDusername();
            }

            public void put(apListLovVORowImpl obj, Object value) {
                obj.setDusername((String)value);
            }
        }
        ,
        Dattributename {
            public Object get(apListLovVORowImpl obj) {
                return obj.getDattributename();
            }

            public void put(apListLovVORowImpl obj, Object value) {
                obj.setDattributename((String)value);
            }
        }
        ,
        Dfullname {
            public Object get(apListLovVORowImpl obj) {
                return obj.getDfullname();
            }

            public void put(apListLovVORowImpl obj, Object value) {
                obj.setDfullname((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(apListLovVORowImpl object);

        public abstract void put(apListLovVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int KEYVALUE = AttributesEnum.KeyValue.index();
    public static final int DUSERNAME = AttributesEnum.Dusername.index();
    public static final int DATTRIBUTENAME = AttributesEnum.Dattributename.index();
    public static final int DFULLNAME = AttributesEnum.Dfullname.index();

    /**
     * This is the default constructor (do not remove).
     */
    public apListLovVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute KeyValue.
     * @return the KeyValue
     */
    public String getKeyValue() {
        return (String) getAttributeInternal(KEYVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KeyValue.
     * @param value value to set the  KeyValue
     */
    public void setKeyValue(String value) {
        setAttributeInternal(KEYVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dusername.
     * @return the Dusername
     */
    public String getDusername() {
        return (String) getAttributeInternal(DUSERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dusername.
     * @param value value to set the  Dusername
     */
    public void setDusername(String value) {
        setAttributeInternal(DUSERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dattributename.
     * @return the Dattributename
     */
    public String getDattributename() {
        return (String) getAttributeInternal(DATTRIBUTENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dattributename.
     * @param value value to set the  Dattributename
     */
    public void setDattributename(String value) {
        setAttributeInternal(DATTRIBUTENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dfullname.
     * @return the Dfullname
     */
    public String getDfullname() {
        return (String) getAttributeInternal(DFULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dfullname.
     * @param value value to set the  Dfullname
     */
    public void setDfullname(String value) {
        setAttributeInternal(DFULLNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
