package CID.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 26 10:39:32 ICT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CidTDCRoleVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CidTDCRoleVOImpl() {
    }
}
