package CID.VO;

import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 27 10:47:29 GMT+07:00 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParentMenuVoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Ffolderguid {
            public Object get(ParentMenuVoRowImpl obj) {
                return obj.getFfolderguid();
            }

            public void put(ParentMenuVoRowImpl obj, Object value) {
                obj.setFfolderguid((String)value);
            }
        }
        ,
        Fparentguid {
            public Object get(ParentMenuVoRowImpl obj) {
                return obj.getFparentguid();
            }

            public void put(ParentMenuVoRowImpl obj, Object value) {
                obj.setFparentguid((String)value);
            }
        }
        ,
        Ffoldername {
            public Object get(ParentMenuVoRowImpl obj) {
                return obj.getFfoldername();
            }

            public void put(ParentMenuVoRowImpl obj, Object value) {
                obj.setFfoldername((String)value);
            }
        }
        ,
        ChildMenuVo {
            public Object get(ParentMenuVoRowImpl obj) {
                return obj.getChildMenuVo();
            }

            public void put(ParentMenuVoRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ParentMenuVoRowImpl object);

        public abstract void put(ParentMenuVoRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FFOLDERGUID = AttributesEnum.Ffolderguid.index();
    public static final int FPARENTGUID = AttributesEnum.Fparentguid.index();
    public static final int FFOLDERNAME = AttributesEnum.Ffoldername.index();
    public static final int CHILDMENUVO = AttributesEnum.ChildMenuVo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParentMenuVoRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Ffolderguid.
     * @return the Ffolderguid
     */
    public String getFfolderguid() {
        return (String) getAttributeInternal(FFOLDERGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Ffolderguid.
     * @param value value to set the  Ffolderguid
     */
    public void setFfolderguid(String value) {
        setAttributeInternal(FFOLDERGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Fparentguid.
     * @return the Fparentguid
     */
    public String getFparentguid() {
        return (String) getAttributeInternal(FPARENTGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Fparentguid.
     * @param value value to set the  Fparentguid
     */
    public void setFparentguid(String value) {
        setAttributeInternal(FPARENTGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Ffoldername.
     * @return the Ffoldername
     */
    public String getFfoldername() {
        return (String) getAttributeInternal(FFOLDERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Ffoldername.
     * @param value value to set the  Ffoldername
     */
    public void setFfoldername(String value) {
        setAttributeInternal(FFOLDERNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ChildMenuVo.
     */
    public RowIterator getChildMenuVo() {
        return (RowIterator)getAttributeInternal(CHILDMENUVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
