package CID.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 27 10:47:31 GMT+07:00 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParentMenuVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ParentMenuVoImpl() {
    }

    /**
     * Returns the bind variable value for groupName.
     * @return bind variable value for groupName
     */
    public String getgroupName() {
        return (String)getNamedWhereClauseParam("groupName");
    }

    /**
     * Sets <code>value</code> for bind variable groupName.
     * @param value value to bind as groupName
     */
    public void setgroupName(String value) {
        setNamedWhereClauseParam("groupName", value);
    }
}
