package CID.VO;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 15 16:05:39 ICT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PheCidListdocrequestVORowImpl extends ViewRowImpl {

    public static final int ENTITY_PHECIDLISTDOCREQUESTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idlist {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getIdlist();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setIdlist((Number) value);
            }
        }
        ,
        Idrequest {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getIdrequest();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setIdrequest((Number) value);
            }
        }
        ,
        Diddoc {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getDiddoc();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setDiddoc((Number) value);
            }
        }
        ,
        Ciddocnumber {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCiddocnumber();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCiddocnumber((String) value);
            }
        }
        ,
        Ciddoctitle {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCiddoctitle();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCiddoctitle((String) value);
            }
        }
        ,
        Ciddocsource {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCiddocsource();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCiddocsource((String) value);
            }
        }
        ,
        Cidcontractor {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidcontractor();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidcontractor((String) value);
            }
        }
        ,
        Cidstatusdocrequest {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidstatusdocrequest();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidstatusdocrequest((String) value);
            }
        }
        ,
        Cidremarkrequestor {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidremarkrequestor();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidremarkrequestor((String) value);
            }
        }
        ,
        Cidremarksv {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidremarksv();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidremarksv((String) value);
            }
        }
        ,
        Cidremarktdc {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidremarktdc();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidremarktdc((String) value);
            }
        }
        ,
        Cidremarktdclead {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidremarktdclead();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidremarktdclead((String) value);
            }
        }
        ,
        Cidusercontractor {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getCidusercontractor();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setCidusercontractor((String) value);
            }
        }
        ,
        booleanApprove {
            protected Object get(PheCidListdocrequestVORowImpl obj) {
                return obj.getbooleanApprove();
            }

            protected void put(PheCidListdocrequestVORowImpl obj, Object value) {
                obj.setbooleanApprove((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }

        protected abstract Object get(PheCidListdocrequestVORowImpl object);

        protected abstract void put(PheCidListdocrequestVORowImpl object, Object value);
    }

    public static final int IDLIST = AttributesEnum.Idlist.index();
    public static final int IDREQUEST = AttributesEnum.Idrequest.index();
    public static final int DIDDOC = AttributesEnum.Diddoc.index();
    public static final int CIDDOCNUMBER = AttributesEnum.Ciddocnumber.index();
    public static final int CIDDOCTITLE = AttributesEnum.Ciddoctitle.index();
    public static final int CIDDOCSOURCE = AttributesEnum.Ciddocsource.index();
    public static final int CIDCONTRACTOR = AttributesEnum.Cidcontractor.index();
    public static final int CIDSTATUSDOCREQUEST = AttributesEnum.Cidstatusdocrequest.index();
    public static final int CIDREMARKREQUESTOR = AttributesEnum.Cidremarkrequestor.index();
    public static final int CIDREMARKSV = AttributesEnum.Cidremarksv.index();
    public static final int CIDREMARKTDC = AttributesEnum.Cidremarktdc.index();
    public static final int CIDREMARKTDCLEAD = AttributesEnum.Cidremarktdclead.index();
    public static final int CIDUSERCONTRACTOR = AttributesEnum.Cidusercontractor.index();
    public static final int BOOLEANAPPROVE = AttributesEnum.booleanApprove.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PheCidListdocrequestVORowImpl() {
    }

    /**
     * Gets PheCidListdocrequestEO entity object.
     * @return the PheCidListdocrequestEO
     */
    public EntityImpl getPheCidListdocrequestEO() {
        return (EntityImpl) getEntity(ENTITY_PHECIDLISTDOCREQUESTEO);
    }

    /**
     * Gets the attribute value for IDLIST using the alias name Idlist.
     * @return the IDLIST
     */
    public Number getIdlist() {
        return (Number) getAttributeInternal(IDLIST);
    }

    /**
     * Sets <code>value</code> as attribute value for IDLIST using the alias name Idlist.
     * @param value value to set the IDLIST
     */
    public void setIdlist(Number value) {
        setAttributeInternal(IDLIST, value);
    }

    /**
     * Gets the attribute value for IDREQUEST using the alias name Idrequest.
     * @return the IDREQUEST
     */
    public Number getIdrequest() {
        return (Number) getAttributeInternal(IDREQUEST);
    }

    /**
     * Sets <code>value</code> as attribute value for IDREQUEST using the alias name Idrequest.
     * @param value value to set the IDREQUEST
     */
    public void setIdrequest(Number value) {
        setAttributeInternal(IDREQUEST, value);
    }

    /**
     * Gets the attribute value for DIDDOC using the alias name Diddoc.
     * @return the DIDDOC
     */
    public Number getDiddoc() {
        return (Number) getAttributeInternal(DIDDOC);
    }

    /**
     * Sets <code>value</code> as attribute value for DIDDOC using the alias name Diddoc.
     * @param value value to set the DIDDOC
     */
    public void setDiddoc(Number value) {
        setAttributeInternal(DIDDOC, value);
    }

    /**
     * Gets the attribute value for CIDDOCNUMBER using the alias name Ciddocnumber.
     * @return the CIDDOCNUMBER
     */
    public String getCiddocnumber() {
        return (String) getAttributeInternal(CIDDOCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDDOCNUMBER using the alias name Ciddocnumber.
     * @param value value to set the CIDDOCNUMBER
     */
    public void setCiddocnumber(String value) {
        setAttributeInternal(CIDDOCNUMBER, value);
    }

    /**
     * Gets the attribute value for CIDDOCTITLE using the alias name Ciddoctitle.
     * @return the CIDDOCTITLE
     */
    public String getCiddoctitle() {
        return (String) getAttributeInternal(CIDDOCTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDDOCTITLE using the alias name Ciddoctitle.
     * @param value value to set the CIDDOCTITLE
     */
    public void setCiddoctitle(String value) {
        setAttributeInternal(CIDDOCTITLE, value);
    }

    /**
     * Gets the attribute value for CIDDOCSOURCE using the alias name Ciddocsource.
     * @return the CIDDOCSOURCE
     */
    public String getCiddocsource() {
        return (String) getAttributeInternal(CIDDOCSOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDDOCSOURCE using the alias name Ciddocsource.
     * @param value value to set the CIDDOCSOURCE
     */
    public void setCiddocsource(String value) {
        setAttributeInternal(CIDDOCSOURCE, value);
    }

    /**
     * Gets the attribute value for CIDCONTRACTOR using the alias name Cidcontractor.
     * @return the CIDCONTRACTOR
     */
    public String getCidcontractor() {
        return (String) getAttributeInternal(CIDCONTRACTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDCONTRACTOR using the alias name Cidcontractor.
     * @param value value to set the CIDCONTRACTOR
     */
    public void setCidcontractor(String value) {
        setAttributeInternal(CIDCONTRACTOR, value);
    }

    /**
     * Gets the attribute value for CIDSTATUSDOCREQUEST using the alias name Cidstatusdocrequest.
     * @return the CIDSTATUSDOCREQUEST
     */
    public String getCidstatusdocrequest() {
        return (String) getAttributeInternal(CIDSTATUSDOCREQUEST);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDSTATUSDOCREQUEST using the alias name Cidstatusdocrequest.
     * @param value value to set the CIDSTATUSDOCREQUEST
     */
    public void setCidstatusdocrequest(String value) {
        setAttributeInternal(CIDSTATUSDOCREQUEST, value);
    }

    /**
     * Gets the attribute value for CIDREMARKREQUESTOR using the alias name Cidremarkrequestor.
     * @return the CIDREMARKREQUESTOR
     */
    public String getCidremarkrequestor() {
        return (String) getAttributeInternal(CIDREMARKREQUESTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDREMARKREQUESTOR using the alias name Cidremarkrequestor.
     * @param value value to set the CIDREMARKREQUESTOR
     */
    public void setCidremarkrequestor(String value) {
        setAttributeInternal(CIDREMARKREQUESTOR, value);
    }

    /**
     * Gets the attribute value for CIDREMARKSV using the alias name Cidremarksv.
     * @return the CIDREMARKSV
     */
    public String getCidremarksv() {
        return (String) getAttributeInternal(CIDREMARKSV);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDREMARKSV using the alias name Cidremarksv.
     * @param value value to set the CIDREMARKSV
     */
    public void setCidremarksv(String value) {
        setAttributeInternal(CIDREMARKSV, value);
    }

    /**
     * Gets the attribute value for CIDREMARKTDC using the alias name Cidremarktdc.
     * @return the CIDREMARKTDC
     */
    public String getCidremarktdc() {
        return (String) getAttributeInternal(CIDREMARKTDC);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDREMARKTDC using the alias name Cidremarktdc.
     * @param value value to set the CIDREMARKTDC
     */
    public void setCidremarktdc(String value) {
        setAttributeInternal(CIDREMARKTDC, value);
    }

    /**
     * Gets the attribute value for CIDREMARKTDCLEAD using the alias name Cidremarktdclead.
     * @return the CIDREMARKTDCLEAD
     */
    public String getCidremarktdclead() {
        return (String) getAttributeInternal(CIDREMARKTDCLEAD);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDREMARKTDCLEAD using the alias name Cidremarktdclead.
     * @param value value to set the CIDREMARKTDCLEAD
     */
    public void setCidremarktdclead(String value) {
        setAttributeInternal(CIDREMARKTDCLEAD, value);
    }

    /**
     * Gets the attribute value for CIDUSERCONTRACTOR using the alias name Cidusercontractor.
     * @return the CIDUSERCONTRACTOR
     */
    public String getCidusercontractor() {
        return (String) getAttributeInternal(CIDUSERCONTRACTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CIDUSERCONTRACTOR using the alias name Cidusercontractor.
     * @param value value to set the CIDUSERCONTRACTOR
     */
    public void setCidusercontractor(String value) {
        setAttributeInternal(CIDUSERCONTRACTOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute booleanApprove.
     * @return the booleanApprove
     */
    public String getbooleanApprove() {
        return (String) getAttributeInternal(BOOLEANAPPROVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute booleanApprove.
     * @param value value to set the  booleanApprove
     */
    public void setbooleanApprove(String value) {
        setAttributeInternal(BOOLEANAPPROVE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

