package CID.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 15 16:05:39 ICT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PheCidListdocrequestVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PheCidListdocrequestVOImpl() {
    }
}

