package CID.Module;

import CID.VO.CIDrunNumberAPVOImpl;
import CID.VO.CidTDCRoleVOImpl;
import CID.VO.ParentMenuVoImpl;
import CID.VO.PheApListVOImpl;
import CID.VO.PheCidListdocrequestVOImpl;
import CID.VO.TdcLeadValVOImpl;
import CID.VO.apListLovVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 01 08:05:01 ICT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DocmetaVO1.
     * @return DocmetaVO1
     */
    public ViewObjectImpl getDocmetaVO1() {
        return (ViewObjectImpl) findViewObject("DocmetaVO1");
    }

    /**
     * Container's getter for DocumenthistoryVO1.
     * @return DocumenthistoryVO1
     */
    public ViewObjectImpl getDocumenthistoryVO1() {
        return (ViewObjectImpl) findViewObject("DocumenthistoryVO1");
    }

    /**
     * Container's getter for DocumentsVO1.
     * @return DocumentsVO1
     */
    public ViewObjectImpl getDocumentsVO1() {
        return (ViewObjectImpl) findViewObject("DocumentsVO1");
    }

    /**
     * Container's getter for ExtitemsVO1.
     * @return ExtitemsVO1
     */
    public ViewObjectImpl getExtitemsVO1() {
        return (ViewObjectImpl) findViewObject("ExtitemsVO1");
    }

    /**
     * Container's getter for FilestorageVO1.
     * @return FilestorageVO1
     */
    public ViewObjectImpl getFilestorageVO1() {
        return (ViewObjectImpl) findViewObject("FilestorageVO1");
    }

    /**
     * Container's getter for FolderfilesVO1.
     * @return FolderfilesVO1
     */
    public ViewObjectImpl getFolderfilesVO1() {
        return (ViewObjectImpl) findViewObject("FolderfilesVO1");
    }

    /**
     * Container's getter for FolderfoldersVO1.
     * @return FolderfoldersVO1
     */
    public ViewObjectImpl getFolderfoldersVO1() {
        return (ViewObjectImpl) findViewObject("FolderfoldersVO1");
    }

    /**
     * Container's getter for FoldersVO1.
     * @return FoldersVO1
     */
    public ViewObjectImpl getFoldersVO1() {
        return (ViewObjectImpl) findViewObject("FoldersVO1");
    }

    /**
     * Container's getter for PheCidCreateVO1.
     * @return PheCidCreateVO1
     */
    public ViewObjectImpl getPheCidCreateVO1() {
        return (ViewObjectImpl) findViewObject("PheCidCreateVO1");
    }

    /**
     * Container's getter for PheCidListdocrequestVO1.
     * @return PheCidListdocrequestVO1
     */
    public PheCidListdocrequestVOImpl getPheCidListdocrequestVO1() {
        return (PheCidListdocrequestVOImpl) findViewObject("PheCidListdocrequestVO1");
    }

    /**
     * Container's getter for PheCidLogVO1.
     * @return PheCidLogVO1
     */
    public ViewObjectImpl getPheCidLogVO1() {
        return (ViewObjectImpl) findViewObject("PheCidLogVO1");
    }

    /**
     * Container's getter for PheCidParticipantVO1.
     * @return PheCidParticipantVO1
     */
    public ViewObjectImpl getPheCidParticipantVO1() {
        return (ViewObjectImpl) findViewObject("PheCidParticipantVO1");
    }

    /**
     * Container's getter for PheConfigVO1.
     * @return PheConfigVO1
     */
    public ViewObjectImpl getPheConfigVO1() {
        return (ViewObjectImpl) findViewObject("PheConfigVO1");
    }

    /**
     * Container's getter for PheContractorVO1.
     * @return PheContractorVO1
     */
    public ViewObjectImpl getPheContractorVO1() {
        return (ViewObjectImpl) findViewObject("PheContractorVO1");
    }

    /**
     * Container's getter for PheDelegateVO1.
     * @return PheDelegateVO1
     */
    public ViewObjectImpl getPheDelegateVO1() {
        return (ViewObjectImpl) findViewObject("PheDelegateVO1");
    }

    /**
     * Container's getter for PheEmailLogVO1.
     * @return PheEmailLogVO1
     */
    public ViewObjectImpl getPheEmailLogVO1() {
        return (ViewObjectImpl) findViewObject("PheEmailLogVO1");
    }

    /**
     * Container's getter for PheRunningnumberVO1.
     * @return PheRunningnumberVO1
     */
    public ViewObjectImpl getPheRunningnumberVO1() {
        return (ViewObjectImpl) findViewObject("PheRunningnumberVO1");
    }

    /**
     * Container's getter for RevisionsVO1.
     * @return RevisionsVO1
     */
    public ViewObjectImpl getRevisionsVO1() {
        return (ViewObjectImpl) findViewObject("RevisionsVO1");
    }

    /**
     * Container's getter for SecuritygroupsVO1.
     * @return SecuritygroupsVO1
     */
    public ViewObjectImpl getSecuritygroupsVO1() {
        return (ViewObjectImpl) findViewObject("SecuritygroupsVO1");
    }

    /**
     * Container's getter for StorageVO1.
     * @return StorageVO1
     */
    public ViewObjectImpl getStorageVO1() {
        return (ViewObjectImpl) findViewObject("StorageVO1");
    }

    /**
     * Container's getter for UsersVO1.
     * @return UsersVO1
     */
    public ViewObjectImpl getUsersVO1() {
        return (ViewObjectImpl) findViewObject("UsersVO1");
    }

    /**
     * Container's getter for UsersecurityattributesVO1.
     * @return UsersecurityattributesVO1
     */
    public ViewObjectImpl getUsersecurityattributesVO1() {
        return (ViewObjectImpl) findViewObject("UsersecurityattributesVO1");
    }

    /**
     * Container's getter for DocumenthistoryRO1.
     * @return DocumenthistoryRO1
     */
    public ViewObjectImpl getDocumenthistoryRO1() {
        return (ViewObjectImpl) findViewObject("DocumenthistoryRO1");
    }

    /**
     * Container's getter for DocmetaRO1.
     * @return DocmetaRO1
     */
    public ViewObjectImpl getDocmetaRO1() {
        return (ViewObjectImpl) findViewObject("DocmetaRO1");
    }

    /**
     * Container's getter for DocumentsRO1.
     * @return DocumentsRO1
     */
    public ViewObjectImpl getDocumentsRO1() {
        return (ViewObjectImpl) findViewObject("DocumentsRO1");
    }

    /**
     * Container's getter for DocumentaccountsRO1.
     * @return DocumentaccountsRO1
     */
    public ViewObjectImpl getDocumentaccountsRO1() {
        return (ViewObjectImpl) findViewObject("DocumentaccountsRO1");
    }

    /**
     * Container's getter for FolderfoldersRO1.
     * @return FolderfoldersRO1
     */
    public ViewObjectImpl getFolderfoldersRO1() {
        return (ViewObjectImpl) findViewObject("FolderfoldersRO1");
    }

    /**
     * Container's getter for FolderfilesRO1.
     * @return FolderfilesRO1
     */
    public ViewObjectImpl getFolderfilesRO1() {
        return (ViewObjectImpl) findViewObject("FolderfilesRO1");
    }

    /**
     * Container's getter for PheCidCreateRO1.
     * @return PheCidCreateRO1
     */
    public ViewObjectImpl getPheCidCreateRO1() {
        return (ViewObjectImpl) findViewObject("PheCidCreateRO1");
    }

    /**
     * Container's getter for PheCidListdocrequestRO1.
     * @return PheCidListdocrequestRO1
     */
    public ViewObjectImpl getPheCidListdocrequestRO1() {
        return (ViewObjectImpl) findViewObject("PheCidListdocrequestRO1");
    }

    /**
     * Container's getter for PheCidListrequestRO1.
     * @return PheCidListrequestRO1
     */
    public ViewObjectImpl getPheCidListrequestRO1() {
        return (ViewObjectImpl) findViewObject("PheCidListrequestRO1");
    }

    /**
     * Container's getter for PheCidLogRO1.
     * @return PheCidLogRO1
     */
    public ViewObjectImpl getPheCidLogRO1() {
        return (ViewObjectImpl) findViewObject("PheCidLogRO1");
    }

    /**
     * Container's getter for PheCidParticipantRO1.
     * @return PheCidParticipantRO1
     */
    public ViewObjectImpl getPheCidParticipantRO1() {
        return (ViewObjectImpl) findViewObject("PheCidParticipantRO1");
    }

    /**
     * Container's getter for PheConfigRO1.
     * @return PheConfigRO1
     */
    public ViewObjectImpl getPheConfigRO1() {
        return (ViewObjectImpl) findViewObject("PheConfigRO1");
    }

    /**
     * Container's getter for PheContractorRO1.
     * @return PheContractorRO1
     */
    public ViewObjectImpl getPheContractorRO1() {
        return (ViewObjectImpl) findViewObject("PheContractorRO1");
    }

    /**
     * Container's getter for PheDelegateRO1.
     * @return PheDelegateRO1
     */
    public ViewObjectImpl getPheDelegateRO1() {
        return (ViewObjectImpl) findViewObject("PheDelegateRO1");
    }

    /**
     * Container's getter for PheEmailLogRO1.
     * @return PheEmailLogRO1
     */
    public ViewObjectImpl getPheEmailLogRO1() {
        return (ViewObjectImpl) findViewObject("PheEmailLogRO1");
    }

    /**
     * Container's getter for RevisionsRO1.
     * @return RevisionsRO1
     */
    public ViewObjectImpl getRevisionsRO1() {
        return (ViewObjectImpl) findViewObject("RevisionsRO1");
    }

    /**
     * Container's getter for StorageRO1.
     * @return StorageRO1
     */
    public ViewObjectImpl getStorageRO1() {
        return (ViewObjectImpl) findViewObject("StorageRO1");
    }

    /**
     * Container's getter for UsersRO1.
     * @return UsersRO1
     */
    public ViewObjectImpl getUsersRO1() {
        return (ViewObjectImpl) findViewObject("UsersRO1");
    }

    /**
     * Container's getter for UsersecurityattributesRO1.
     * @return UsersecurityattributesRO1
     */
    public ViewObjectImpl getUsersecurityattributesRO1() {
        return (ViewObjectImpl) findViewObject("UsersecurityattributesRO1");
    }

    /**
     * Container's getter for PHE_CID_LISTDOCREQUEST1.
     * @return PHE_CID_LISTDOCREQUEST1
     */
    public ViewObjectImpl getPHE_CID_LISTDOCREQUEST1() {
        return (ViewObjectImpl) findViewObject("PHE_CID_LISTDOCREQUEST1");
    }

    /**
     * Container's getter for ParentMenuVo1.
     * @return ParentMenuVo1
     */
    public ParentMenuVoImpl getParentMenuVo1() {
        return (ParentMenuVoImpl) findViewObject("ParentMenuVo1");
    }

    /**
     * Container's getter for PheCidListrequestVO1.
     * @return PheCidListrequestVO1
     */
    public ViewObjectImpl getPheCidListrequestVO1() {
        return (ViewObjectImpl) findViewObject("PheCidListrequestVO1");
    }

    /**
     * Container's getter for tdcLead1.
     * @return tdcLead1
     */
    public ViewObjectImpl gettdcLead1() {
        return (ViewObjectImpl) findViewObject("tdcLead1");
    }

    /**
     * Container's getter for ChildMenuVo1.
     * @return ChildMenuVo1
     */
    public ViewObjectImpl getChildMenuVo1() {
        return (ViewObjectImpl) findViewObject("ChildMenuVo1");
    }

    /**
     * Container's getter for ChildMenuVo2.
     * @return ChildMenuVo2
     */
    public ViewObjectImpl getChildMenuVo2() {
        return (ViewObjectImpl) findViewObject("ChildMenuVo2");
    }

    /**
     * Container's getter for UserInternalVO1.
     * @return UserInternalVO1
     */
    public ViewObjectImpl getUserInternalVO1() {
        return (ViewObjectImpl) findViewObject("UserInternalVO1");
    }

    /**
     * Container's getter for TDCEmailCC1.
     * @return TDCEmailCC1
     */
    public ViewObjectImpl getTDCEmailCC1() {
        return (ViewObjectImpl) findViewObject("TDCEmailCC1");
    }

    /**
     * Container's getter for PheCidAttachmentVO1.
     * @return PheCidAttachmentVO1
     */
    public ViewObjectImpl getPheCidAttachmentVO1() {
        return (ViewObjectImpl) findViewObject("PheCidAttachmentVO1");
    }

    /**
     * Container's getter for PheCidAttachmentRO1.
     * @return PheCidAttachmentRO1
     */
    public ViewObjectImpl getPheCidAttachmentRO1() {
        return (ViewObjectImpl) findViewObject("PheCidAttachmentRO1");
    }

    /**
     * Container's getter for PheCidCreatePurposeVO1.
     * @return PheCidCreatePurposeVO1
     */
    public ViewObjectImpl getPheCidCreatePurposeVO1() {
        return (ViewObjectImpl) findViewObject("PheCidCreatePurposeVO1");
    }

    /**
     * Container's getter for monitoringVO1.
     * @return monitoringVO1
     */
    public ViewObjectImpl getmonitoringVO1() {
        return (ViewObjectImpl) findViewObject("monitoringVO1");
    }

    /**
     * Container's getter for HistoryCIDVO1.
     * @return HistoryCIDVO1
     */
    public ViewObjectImpl getHistoryCIDVO1() {
        return (ViewObjectImpl) findViewObject("HistoryCIDVO1");
    }

    /**
     * Container's getter for LastRejectVO1.
     * @return LastRejectVO1
     */
    public ViewObjectImpl getLastRejectVO1() {
        return (ViewObjectImpl) findViewObject("LastRejectVO1");
    }

    /**
     * Container's getter for PheApListVO1.
     * @return PheApListVO1
     */
    public PheApListVOImpl getPheApListVO1() {
        return (PheApListVOImpl) findViewObject("PheApListVO1");
    }

    /**
     * Container's getter for TdcLeadValVO1.
     * @return TdcLeadValVO1
     */
    public TdcLeadValVOImpl getTdcLeadValVO1() {
        return (TdcLeadValVOImpl) findViewObject("TdcLeadValVO1");
    }

    /**
     * Container's getter for apListLovVO1.
     * @return apListLovVO1
     */
    public apListLovVOImpl getapListLovVO1() {
        return (apListLovVOImpl) findViewObject("apListLovVO1");
    }

    /**
     * Container's getter for CIDrunNumberAPVO1.
     * @return CIDrunNumberAPVO1
     */
    public CIDrunNumberAPVOImpl getCIDrunNumberAPVO1() {
        return (CIDrunNumberAPVOImpl) findViewObject("CIDrunNumberAPVO1");
    }

    /**
     * Container's getter for CidTDCRoleVO1.
     * @return CidTDCRoleVO1
     */
    public CidTDCRoleVOImpl getCidTDCRoleVO1() {
        return (CidTDCRoleVOImpl) findViewObject("CidTDCRoleVO1");
    }

    /**
     * Container's getter for DetailCID1.
     * @return DetailCID1
     */
    public ViewObjectImpl getDetailCID1() {
        return (ViewObjectImpl) findViewObject("DetailCID1");
    }

    /**
     * Container's getter for ParentViewLink1.
     * @return ParentViewLink1
     */
    public ViewLinkImpl getParentViewLink1() {
        return (ViewLinkImpl) findViewLink("ParentViewLink1");
    }

    /**
     * Container's getter for ChildViewLink1.
     * @return ChildViewLink1
     */
    public ViewLinkImpl getChildViewLink1() {
        return (ViewLinkImpl) findViewLink("ChildViewLink1");
    }
}

